# Generated by Django 5.2.6 on 2025-09-19 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('tel_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone must be 7–15 digits, optional leading '+'.", regex='^\\+?\\d{7,15}$')], verbose_name='Telephone')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='myapp1_cont_name_2ec0d2_idx'), models.Index(fields=['email'], name='myapp1_cont_email_4c898c_idx')],
            },
        ),
    ]
