# Generated by Django 5.2.6 on 2025-10-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_contact_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
